### ISSUE TITLE
Master Worker Error

### ISSUE THREAD

**Issue by aericc** [ForlaxPy/openbullet-1.2#13]
Hi, I started having this issue after the new update was forced upon me, (so sadly I had no choice :(, please let us be able to use or revert to previous versions next time), and it displayed this error message. 
![Capture](https://user-images.githubusercontent.com/49380667/55693676-40d59000-597e-11e9-8cb0-8fb9b0abcb63.PNG)
This would happen after I loaded my config and combo and tried pressing "Start". I would like to know if there was a fix for this or it is an update issue. Thanks.

~ eric
=================================================================
Edit: Got it working, must've been a new update or something. Don't know if you included a txt file for us to read, but if you did my bad aha. Basically if anyone else is having the issue, you need to edit the config and look for "AllowedWordlist1": "", and in between the last "", you put either MailPass, UserPass, etc. I don't think I can edit loliX files but hopefully they work (haven't tested them yet). Thank god my small brain didn't take long to process.

~ eric

**Comment by ForlaxPy** [comment]
For .loliX files it will auto fix it self don't worry. Well the issue is that everyone got used to BB that auto does that xD But I just added it automatically in OB but you still need to fix it in the old configs. Anyway you won't face it in the upcoming configs so don't worry ^^
