### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by shdf2** [ForlaxPy/openbullet-1.2#16]
Hello,
wouldn't it be better to make a "Check for update" button or schedule instead of an automatic update after each program start ?
i'm sure many of use would prefer to keep control and decide if they want to update or not...

Just a suggestion. :-)

Sory to insert this message in the issue, i don't know where to add a comment...

**Comment by ForlaxPy** [comment]
Yeh ofc I will do that I just added the auto updater for now as seems that OB isn't really stable so I will be working on adding bunch of features and fixing bugs daily and that would auto updates your files for the best performances and experience. Will for sure remove it later after getting a stable release.
