### ISSUE TITLE
Instant Crash on Proxy Import 

### ISSUE THREAD

**Issue by PurityWasHere** [ForlaxPy/openbullet-1.2#22]
Program will immediately crash when i click Import proxies. Wasn't happening a few hours ago, Theres been no Commits recently. How weird

**Comment by vajeeking** [comment]
same here worked older releases  good,, but now force update newest instant crash. when import proxies.

**Comment by damith48** [comment]
same error come to me...
please fix this
thx

**Comment by flyal** [comment]
Hello
Same error come to me...
please fix this
Thanks

**Comment by ForlaxPy** [comment]
Fixed the issues was from proxyscrape host. Sorry for the inconvenience .
