### ISSUE TITLE
Proxyscraper Missing

### ISSUE THREAD

**Issue by flyal** [ForlaxPy/openbullet-1.2#5]
Hello
Why in the source code the option Proxyscraper is missing .
Please can you add also it.
Thnx Very Much

![image](https://user-images.githubusercontent.com/7648746/55685329-14f1e480-5955-11e9-9605-1a4b7f78613f.png)

**Comment by ForlaxPy** [comment]
Yes actually I just added it in the release bin but forgot to do in the src code will add it as soon as possible
