### ISSUE TITLE
problem with captcha box and custom keys are missing

### ISSUE THREAD

**Issue by bfx002** [ForlaxPy/openbullet-1.2#7]
so i tried captcha its not downloading the image sometimes it gives error image type not supported and many time its just giving one digit response. made it on BB its working just fine. and second issue is custom keys 1.0.0 have option to select custom keys type like free, 2 FA and etc. these options are missing

**Comment by ShadixAced** [comment]
I'll take this one a shot.

1) Are your keys inserted into OpenBullet ? If yes, is your balance OK ?
2) This one is more of an configuration issue than OpenBullet's fault. Try to check with the debugger the result the config's giving, and you might have some chances to fix it.

**Comment by ForlaxPy** [comment]
1- Well for captcha I don't recommend using or working with it atm as it's still bugged on OpenBullet the issue is already open in here https://github.com/openbullet/openbullet/issues/10 waiting for OB Devs to fix it. 
2- For custom keys I just added FREE one I will make sure to add all the others from BB latest version to it.

**Comment by bfx002** [comment]
@ForlaxPy isnt it possible to give users choice that what name should one choose for custom key. like while selecting custom it ask for key name. it would be really helpful for all. and also make a documentation for LOLIX DB API encryption method. 
Keep up the good work

**Comment by ForlaxPy** [comment]
Nah I don't think that would be possible atm as it will take a while to update it, it's fully linked to Environment.ini, you can in the meanwhile add your custom keys as you want just edit Environment.ini in the settings folder. Here is the format:
![pic](https://i.imgur.com/fJ0f6a6.png)
