### ISSUE TITLE
Fiddler

### ISSUE THREAD

**Issue by GunmanUK** [ForlaxPy/openbullet-1.2#8]
I use fiddler to make my OB configs. Can you add an option so that Fiddler doesn't make your modded version of OB close? It's quite annoying, as other people think so  as well.

**Comment by ForlaxPy** [comment]
Yes several ppl reported this. Will make sure to fix it in the upcoming versions

**Comment by GunmanUK** [comment]
Thank you so much! Sick mod btw, loving it!
