### ISSUE TITLE
Force Content-type header for get requests

### ISSUE THREAD

**Issue by supritobiswas** [ForlaxPy/openbullet-1.2#9]
Trying to force OB to send "Content-Type: application/json" in header for a GET request, but it's omitting it. It only sends that header for POST requests atm. Some configs require that I send the 'Content-Type: application/json' header for GET also. Couldn't find a workaround. Can you please help?

Thanks. Awesome work btw. :)

**Comment by ForlaxPy** [comment]
sure will implement this on the next upcoming version ^^

**Comment by ForlaxPy** [comment]
Actually it works with Both POST and GET just make sure you don't leave the post Data empty maybe something like {} 
[!pic](https://i.imgur.com/zuWF0r8.png)
![pic1](https://i.imgur.com/f5FeETg.png)

I can easily remove that but idk I just don't feel like to do that as it may ruin a lot of ppls works.

**Comment by bfx002** [comment]
@supritobiswas adding Content-Type: application/json in custom headers is not working with GET requests ?

**Comment by ForlaxPy** [comment]
You don't acualy need to add it from the custom headers just do it in the content type given in there. I mean if we get in depth, in GET method you're not sending anything to the host so you don't need a content type to be sent you're just getting something but you still can use it if you don't leave the post data empty

**Comment by supritobiswas** [comment]
no, i already tried out 
1. what @ForlaxPy showed above, i.e. keeping something in post-data
2. keeping it in custom headers

i even tried to trick OB by keeping "\nContent-Type: application/json" in a variable and feeding it into custom headers! that failed terribly though. XD

thanks Forlax for adding it <3

**Comment by ForlaxPy** [comment]
Well I added it but you still have to keep something in the post data, in your case if it's nothing just make it " {} " . Anyway you will get used to it and the updated one will prob come out tomorrow .

**Comment by supritobiswas** [comment]
@ForlaxPy tried the latest update. It still doesn't seem to work.

I put the {} as you said in the post data, made it a GET request. Debug shows the 'Content-Type: application/json' header is being sent.

However, it's not actually sending it. I checked the actual request in fiddler. The content header is still missing.

Attaching pictures. The site I'm trying is hotstar (API).

![Screenshot_1](https://user-images.githubusercontent.com/49371732/55730485-f0216e00-5a35-11e9-9d81-312f197b0f93.png)
![Screenshot_2](https://user-images.githubusercontent.com/49371732/55730486-f0216e00-5a35-11e9-80a0-ff23889fb9db.png)
